export const FilterTypes = {
    ALL: "all",
    AUTHOR: "author",
    LANGUAGE: "language",
    COUNTRY_OF_PUBLICATION: "countryOfPublication",
    CITY_OF_PUBLICATION: "cityOfPublication",
    PUBLICATION_TYPE: "publicationType",
    PUBLISHER: "publisher",
    SUBJECT: "subject",
    TITLE: "title",
    YEAR_OF_PUBLICATION: "yearOfPublication"
};

export const allFields = [ "book_author",
    "book_title",
    "book_parallel_title",
    "book_sub_title",
    "book_publisher",
    "book_printer",
    "book_publication_country",
    "book_publication_city",
    "book_publication_year",
    "book_publication_number",
    "book_shape",
    "book_height",
    "book_volumes",
    "book_pages",
    "book_pagination",
    "book_illustration",
    "book_publication_type",
    "book_bibliography",
    "book_subject",
    "included_book_author",
    "included_book_title",
    "series_title",
    "volume_number",
    "magazine_title",
    "magazine_opuscule",
    "magazine_volume",
    "newspaper_title",
    "newspaper_volume",
    "idological_classification",
    "cronological_classification",
    "thematical_classification",
    "tekmirio_language",
    "prototype",
    "original_language",
    "original_translated_language",
    "libraries",
    "url",
    "contributors",
    "funding",
    "copublished_book_author",
    "copublished_book_title",
    "other_publication",
    "other_publication_type",
    "republication_title",
    "republication_publisher",
    "republication_instructor",
    "republication_place",
    "republication_year",
    "title_page_text",
    "kolofonas_text",
    "description",
    "prototype_author",
    "prototype_title",
    "prototype_parallel_title",
    "prototype_subtitle",
    "prototype_publisher",
    "prototype_printer",
    "prototype_publication_country",
    "prototype_publication_city",
    "prototype_publication_year",
    "prototype_shape",
    "prototype_volumes",
    "prototype_pages",
    "prototype_pagination",
    "prototype_illustration",
    "prototype_publication_type",
    "prototype_original_prototype",
    "prototype_original_language",
    "translated_prototype_original_language",
    "prototype_description",
    "prototype_url"];